version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: glebastaa/foodgram_backend:latest
    restart: always
    volumes:
      - foodgram_static:/app/static_backend/
      - foodgram_media:/app/media_backend/
      - api_docs:/app/docs/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: glebastaa/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - api_docs:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static_backend/
      - foodgram_media:/var/html/media_backend/

    depends_on:
      - frontend


volumes:
  postgres_data:
  foodgram_static:
  foodgram_media:
  api_docs:
